# See https://www.appveyor.com/docs/appveyor-yml for appveyor documention.
build: off
image: Visual Studio 2017
version: '{build}'
branches:
  only:
    - master
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%LOCALAPPDATA%\Yarn'
platform: x64
environment:
  nodejs_version: 8
install:
  - choco install yarn
  - refreshenv
  - yarn
  - yarn build
test_script:
  - yarn lint
  - yarn flow
  - yarn test -- --coverage
