# See https://www.appveyor.com/docs/appveyor-yml for appveyor documention.
build: off
image: Visual Studio 2017
version: '{build}'
branches:
  only:
    - master
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%APPDATA%\ESLint'
  - '%APPDATA%\Jest'
  - '%LOCALAPPDATA%\Yarn'
platform: x64
environment:
  nodejs_version: 8
  APPVEYOR_CACHE_SKIP_RESTORE: true
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - choco install yarn
  - refreshenv
  - yarn
  - yarn lerna link
  - yarn build
test_script:
  - yarn lint --cache --cache-location %APPDATA%\ESLint
  - yarn flow
  - yarn test --coverage --cacheDirectory %APPDATA%\Jest
  - yarn codecov
