# See https://circleci.com/docs/2.0 for circleci documention.
version: 2
jobs:
  build:
    docker:
      - image: node:latest
        environment:
          YARN_VERSION: '1.0.1'
    working_directory: ~/orio
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: |
            apt-get update && \
            apt-get install -y libelf1 && \
            yarn global add greenkeeper-lockfile@1 && \
            yarn && \
            yarn build
      - save_cache:
          key: dependency-cache-{{ epoch }}
          paths:
            - ~/.cache/yarn
            - ~/.yarn
            - ~/.yarn-cache
      - run:
          name: Greenkeeper Lockfile Update
          command: greenkeeper-lockfile-update
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Check Types
          command: yarn flow
      - run:
          name: Test
          command: yarn test -- --coverage
      - run:
          name: Report Coverage
          command: yarn codecov
      - run:
          name: Greenkeeper Lockfile Upload
          command: greenkeeper-lockfile-upload
