// flow-typed signature: db6ba747698a3f43b9bd91966f698e20
// flow-typed version: <<STUB>>/babel-minify_v^0.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-minify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-minify/__tests__/cli-tests' {
  declare module.exports: any;
}

declare module 'babel-minify/__tests__/fixtures/out-dir/a/foo' {
  declare module.exports: any;
}

declare module 'babel-minify/__tests__/fixtures/out-file/foo' {
  declare module.exports: any;
}

declare module 'babel-minify/__tests__/node-api-tests' {
  declare module.exports: any;
}

declare module 'babel-minify/bin/minify' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/cli' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/fs' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/index' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/options-parser' {
  declare module.exports: any;
}

declare module 'babel-minify/src/cli' {
  declare module.exports: any;
}

declare module 'babel-minify/src/fs' {
  declare module.exports: any;
}

declare module 'babel-minify/src/index' {
  declare module.exports: any;
}

declare module 'babel-minify/src/options-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-minify/__tests__/cli-tests.js' {
  declare module.exports: $Exports<'babel-minify/__tests__/cli-tests'>;
}
declare module 'babel-minify/__tests__/fixtures/out-dir/a/foo.js' {
  declare module.exports: $Exports<'babel-minify/__tests__/fixtures/out-dir/a/foo'>;
}
declare module 'babel-minify/__tests__/fixtures/out-file/foo.js' {
  declare module.exports: $Exports<'babel-minify/__tests__/fixtures/out-file/foo'>;
}
declare module 'babel-minify/__tests__/node-api-tests.js' {
  declare module.exports: $Exports<'babel-minify/__tests__/node-api-tests'>;
}
declare module 'babel-minify/bin/minify.js' {
  declare module.exports: $Exports<'babel-minify/bin/minify'>;
}
declare module 'babel-minify/lib/cli.js' {
  declare module.exports: $Exports<'babel-minify/lib/cli'>;
}
declare module 'babel-minify/lib/fs.js' {
  declare module.exports: $Exports<'babel-minify/lib/fs'>;
}
declare module 'babel-minify/lib/index.js' {
  declare module.exports: $Exports<'babel-minify/lib/index'>;
}
declare module 'babel-minify/lib/options-parser.js' {
  declare module.exports: $Exports<'babel-minify/lib/options-parser'>;
}
declare module 'babel-minify/src/cli.js' {
  declare module.exports: $Exports<'babel-minify/src/cli'>;
}
declare module 'babel-minify/src/fs.js' {
  declare module.exports: $Exports<'babel-minify/src/fs'>;
}
declare module 'babel-minify/src/index.js' {
  declare module.exports: $Exports<'babel-minify/src/index'>;
}
declare module 'babel-minify/src/options-parser.js' {
  declare module.exports: $Exports<'babel-minify/src/options-parser'>;
}
