// flow-typed signature: 02efe2277ea399ee6fe709dfb973da76
// flow-typed version: <<STUB>>/lazy.js_v^0.5.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lazy.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lazy.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lazy.js/autodoc/handlers' {
  declare module.exports: any;
}

declare module 'lazy.js/experimental/lazy.es6' {
  declare module.exports: any;
}

declare module 'lazy.js/experimental/lazy.json' {
  declare module.exports: any;
}

declare module 'lazy.js/lazy' {
  declare module.exports: any;
}

declare module 'lazy.js/lazy.min' {
  declare module.exports: any;
}

declare module 'lazy.js/lazy.node' {
  declare module.exports: any;
}

declare module 'lazy.js/perf/perf_race' {
  declare module.exports: any;
}

declare module 'lazy.js/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lazy.js/autodoc/handlers.js' {
  declare module.exports: $Exports<'lazy.js/autodoc/handlers'>;
}
declare module 'lazy.js/experimental/lazy.es6.js' {
  declare module.exports: $Exports<'lazy.js/experimental/lazy.es6'>;
}
declare module 'lazy.js/experimental/lazy.json.js' {
  declare module.exports: $Exports<'lazy.js/experimental/lazy.json'>;
}
declare module 'lazy.js/lazy.js' {
  declare module.exports: $Exports<'lazy.js/lazy'>;
}
declare module 'lazy.js/lazy.min.js' {
  declare module.exports: $Exports<'lazy.js/lazy.min'>;
}
declare module 'lazy.js/lazy.node.js' {
  declare module.exports: $Exports<'lazy.js/lazy.node'>;
}
declare module 'lazy.js/perf/perf_race.js' {
  declare module.exports: $Exports<'lazy.js/perf/perf_race'>;
}
declare module 'lazy.js/util.js' {
  declare module.exports: $Exports<'lazy.js/util'>;
}
