// flow-typed signature: 6d8585f484dc087ddeed75d3f77fac93
// flow-typed version: <<STUB>>/microtime_v^2.1.6/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'microtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'microtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'microtime/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'microtime/index' {
  declare module.exports: $Exports<'microtime'>;
}
declare module 'microtime/index.js' {
  declare module.exports: $Exports<'microtime'>;
}
declare module 'microtime/test.js' {
  declare module.exports: $Exports<'microtime/test'>;
}
