// flow-typed signature: 203673a017d15352eda7d27afb03955d
// flow-typed version: <<STUB>>/rollup-plugin-babel-minify_v3.1.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-babel-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-babel-minify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify.es2015' {
  declare module.exports: any;
}

declare module 'rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify.es2015.js' {
  declare module.exports: $Exports<'rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify.es2015'>;
}
declare module 'rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify.js' {
  declare module.exports: $Exports<'rollup-plugin-babel-minify/dist/rollup-plugin-babel-minify'>;
}
