// flow-typed signature: 8f44afbdb2d314d6586c0a530a99e9e6
// flow-typed version: <<STUB>>/web-streams-polyfill_v1.3.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-streams-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-streams-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-streams-polyfill/dist/polyfill' {
  declare module.exports: any;
}

declare module 'web-streams-polyfill/dist/polyfill.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-streams-polyfill/dist/polyfill.js' {
  declare module.exports: $Exports<'web-streams-polyfill/dist/polyfill'>;
}
declare module 'web-streams-polyfill/dist/polyfill.min.js' {
  declare module.exports: $Exports<'web-streams-polyfill/dist/polyfill.min'>;
}
